name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 11 (your project uses Java 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Build with Maven (compile + test)
      - name: Build with Maven
        run: mvn -B clean verify

      # Build Docker image (tag with commit SHA)
      - name: Build Docker image
        run: docker build -t spring-boot-cicd:${{ github.sha }} .

      # Sanity check container runs and health endpoint responds
      - name: Run container sanity check
        run: |
          docker run -d -p 8080:8080 --name test-app spring-boot-cicd:${{ github.sha }}
          echo "Waiting for app to start..."
          sleep 20
          curl --fail http://localhost:8080/actuator/health
          docker stop test-app
          docker rm test-app
